server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      sampling:
        probability: 1.0